### ISSUE TITLE
Draft: Novo processo de deploy

### ISSUE THREAD

**Issue by mccraveiro** [pagarme/handbook#1]
Gostaria de abrir aqui a discussão sobre como podemos melhorar nosso processo de deploy atual e como podemos implementar isso. Abaixo segue uma sugestão. Fiquem livres para critica-la. 

### Problema atual
Com o crescente numero de devs, começamos a ter problemas com concorrência em deploys e visibilidade. 

### Solução proposta
Minha sugestão é a utilização de ciclos de deploy de uma semana. Assim, teríamos 3 branches principais: master, staging e release (nomes estão abertos a discussão). Toda segunda-feira o código da master iria para staging e o de staging seria deployed na release. Isso não remove a necessidade de rolling deploy em produção, do monitoramento das mesmas, alem dos reviews das PRs antes de entrar na master.

### Pontos Positivos

- Acaba com a fila de deploy.
- Agiliza o tempo de desenvolvimento sem afetar a qualidade.
- Pequenos fixes e melhorias de código não são penalizados pelo custo fixo de deploy atual.
- Features novas ficam mais tempo num ambiente de teste antes de passarem para produção. 
- Reduz a reclamação dos clientes de deploys contantes em horário comercial.

### Pontos Negativos

- Features novas demoram mais para entrarem em produção. 
- Breaking changes devem ser patched na release e depois nas outras branches (Cherry Pick).
- Aumenta a dificuldade de identificar qual PR criou determinado bug.

**Comment by mccraveiro** [comment]
Então, o deploy seria sempre no mesmo dia semanalmente. Porem, como dev, você poderia dar merges em PRs em qualquer dia da semana, tendo em mente que só estará em produção na semana seguinte.

**Comment by MarcoWorms** [comment]
Entendi, acho bacana, eu toparia seguir um modelo que tenha staging.

**Comment by felquis** [comment]
@mccraveiro vale a pena ver como funciona o deploy dos projetos que usam CDN, pois parece ser um pouco diferente. (dash e checkout)

**Comment by mccraveiro** [comment]
Um ponto que foi levantado é que uma semana é muito tempo para o nosso modelo de negocio. Gostaria de deixar claro que isso pode ser ajustado. Ja trabalhei com 15 dias, mas podemos trabalhar com um tempo menor. O ponto é: fazer deploy de feature por feature e monitorar isso não é escalável com a quantidade de PRs que temos.

**Comment by MarcoWorms** [comment]
Cara, não sei se uma semana e muito tempo não, ja vi várias vezes a pessoa demorar 1 semana pra deploiar pq nunca consegue. Dado uma data fixa pra isso a gente ganha previsibilidade, eu diria pra começarmos com algo que faça sentido sem muito over-thinking e a gente itera em cima do processo até ele ficar adequado para nós :)

**Comment by osmanpontes** [comment]
O que fazemos quando 5 features forem deployadas e ocorrer um erro em produção?
A dificuldade aumenta, como o @mccraveiro comentou, mas qual o processo?
Nesse caso em particular deployamos cada umas dessas 5, de uma por uma, até ver qual delas causou o problema?

Pra mim essa mudança exige um esforço do nosso lado de simular as features com dados reais num servidor de staging antes colocar em produção.
Quando colocar várias features juntas e der certo, vai ser ótimo.
Mas quando der errado, vamos acabar voltando ao processo atual (que é ruim).

Essa decisão pra mim está ligada a quantidade de vezes que encontramos problema quando deployamos. Se for pequena, então vale a pena experimentar. Se for alta, vai gerar mais trabalho do que solução.

De qualquer modo, a sugestão do @MarcoWorms é válida: podemos mudar para fazer semanalmente e ver como é na prática. Se passarmos por esse problema que estou falando , descobriremos se ele é relevante.

**Comment by derekstavis** [comment]
Eu não gosto muito dos modelos baseados em "git flow", que contém uma branch intermediária para integracão, qual segue a premissa de ser a branch pré-producao, ou seja, que deve estar "redonda". 

Seguem os principais problemas que eu já passei e creio que desejamos evitar:

- **Dificuldade de releases emergenciais:** Quando algo vai pra master em caráter de emergência, force pushes na branch de integracão são necessários, resultando em tretas pra todo mundo que tem uma cópia da branch.
- **Difícil reversão de commits:** Novamente, qualquer coisa que precise ser revertida gera ou um commit de revert (o que é bastante nojento) ou um force push na branch de integracao
- **Sem diferenca entre a master:** No final das contas tudo é uma medida protetiva pra não entrar nada na master, o que torna a branch de integracao, basicamente uma master.

[Este post do StackOverflow](http://stackoverflow.com/a/35915110/1429720) também é muito bom e esclarecedor sobre os três modelos de Git que temos:

---

**Multiple versions in production - use Git-flow**
>If your code is having multiple versions in production (i.e. typical software products like Operating Systems, Office Packages, Custom applications, etc) you may use git-flow. Main reason is that you need to continuously support previous versions in production while developing the next version.

**Single version in production simple software - use Github-flow**
>If your code is having only one version in production at all times (i.e. web sites, web services, etc) you may use github-flow. Main reason is that you don't need to complex things for the developer. Once developer finish a feature or finish a bugfix its immediately promoted to production version.

**Single Version in production but very complex software - use Gitlab-flow**
>Large software like Facebook and Gmail, you may need to introduce deployment branches between your branch and master branch where CI/CD > tools could run, before it gets in to production. Idea is to introduce more protection to production version since its used by millions of people.

----

Outro modelo legal é o de **release trains**, onde periodicamente o trem do deploy passa pelos squads coletando coisas que podem estar prontas para serem lancadas, e fica responsável por:

1. Integrar as mudancas em uma branch *prepare-for-release*
2. Verificar se após a integracão todos os testes passam
3. Fazer o deploy em staging (production/test) e avaliar o resultado
4. Fazer o merge da branch na master
5. Deployar a master, verificar se tudo correu bem, fazendo rollback em caso de erro

Além da discussão de fluxo, vale lembrar que o squad @pagarme/infrastructure está trabalhando na nova infra (que trará o monorepo a vida), e deve ser incluída nesta discussão para que o novo processo de deploy leve em consideracão todas as dores dos desenvolvedores.

**Comment by derekstavis** [comment]
Em nosso contexto poderíamos pensar em algo assim:

- Squads resolvem demandas de produto em **feature branches**
  + *Resolver aqui significa desenvolver e testar em escopo local + ci + sandbox*
- Demandas de produto finalizadas geram demandas de **deploy**
- Diariamente (*daily!*) os squads se reúnem pra falar de deploy
- Os squads trazem **demandas de deploy**
- Um novo **release squad** é criado com um dev de cada **demanda de deploy**.

O **release squad** é responsável por:

- Integrar as **feature branches** em uma **única branch**
- Deployar e **monitorar** em **staging**
- Deployar para **production**

A vantagem de um modelo desse é que traz uma pessoa experiente de cada squad junto ao processo de deploy, permitindo deployar em bulk várias features de uma vez só, facilitando o monitoramento e também a reversão de qualquer problema que venha a acontecer.

**Comment by mccraveiro** [comment]
@derekstavis Ótimos inputs! Podemos começar testando esse modelo de **release squad** porém essas "reuniões" diárias para deploys podem acabar sobrecarregando alguém só para isso. 

Spotify faz uso de **release trains**, mas no modelo deles até features inacabadas são deployadas atrás de **feature flags** (podemos debatar isso em outra issue). No nosso caso como iriamos fazer essa distinção entre o que pode ser deployado em cada squad? 

Outro modelo que achei bem interessante é a de **release branches**. Neste caso a master é a única branch ativa e para cada deploy em produção é criada uma nova release branch a partir daquele ponto da master (usando semver). Assim, hotfixes entram na master e podem ser cherry picked para essa release branch sem os problemas que você citou acima pois um novo deploy iria finalizar aquela branch e criar uma nova com todos os hot fixes passados e novas features (tudo que já está na master).

**Comment by greenboxal** [comment]
Eu não acho que versionamento é uma coisa boa pro nosso processo. Temos uma aplicação gigante com centenas de features que são mexidas diariamente. Essas features deveriam ser independentes, apesar de estarem na mesma aplicação.

**Comment by hails** [comment]
O que eu gostaria em D+0 seria uma "agenda" de deploys.
Saber quais deploys estao acontecendo e, na semana, quais estao planejados.
Vejo dois tipos de deploys:
- um que é algo nao muito sensivel e que em um dia já consegue passar pelo processo de `test` -> `merge` -> `live`
- outro que é mais sensível e precisa ser mais cauteloso, levando até tres dias para ser mergeado e deployado em live
Isso tudo por serviço (`api`, `gateway` etc), assim acho que nao engessaria o processo mas tambem nao seria a zona que está hoje.

**Comment by mccraveiro** [comment]
@greenboxal Por mim não precisa usar versionamento também. So dei a sugestão para conseguirmos fazer auditoria do que foi deployado quando. Hoje, não sabemos exatamente qual "versão" esta em produção. E usar uma unica branch release tem os side effects que o @derekstavis comentou acima. 

@hails O problema de agendar deploys em períodos irregulares é a falta de visibilidade. Se tiver um horário ou dia exato, nenhum dev precisa "pensar" em quando isso vai pra produção. Vira algo mais simples: Ta na master, no dia tal estará em produção. Sobre a separação de serviços, como fazer isso com o monorepo e features que dependem de mais de um serviço?

**Comment by hails** [comment]
@mccraveiro nao estou pensando no futuro, essa sugestao foi pra D+0 mesmo, enquanto discutimos o que fazer no medio e longo prazo.

**Comment by MarcoWorms** [comment]
BUMP, e ai, como vai esse assunto?

**Comment by mccraveiro** [comment]
Acho que inicialmente deveríamos documentar melhor o processo atual. Conversando com diversas pessoas, percebi que cada um faz deploy de uma maneira apesar das especificações do template de PR. Semana passada, o @felquis levantou individualmente como deveria ser o processo no geral e ficou de documentar isso em algum lugar. Temos um update? 

Alem disso, seria interessante trabalhar inicialmente nesta visibilidade de deploys, de preferencial com histórico e filas individuais de cada serviço. A sharon ja tem parte dessas features, mas acho que poderíamos trabalhar em alguma solução mais robusta. Ideias?

PS: Faz sentido continuar essa discussão aqui? Ou movemos para o forum?

**Comment by derekstavis** [comment]
Opa, acho que o @oPorks pode nos ajudar a estruturar algo com base na thread!

**Comment by grvcoelho** [comment]
Moved
