### ISSUE TITLE
Sala de reunião

### ISSUE THREAD

**Issue by cesasrmoori** [pagarme/handbook#6]
Precisamos de uma política para sala de reuniões.

**Comment by Lcastellari** [comment]
Reserva de salas de reunião

As salas do pagar.me devem ser reservadas previamente antes de serem utilizadas para reuniões, assim evitando conflitos para o uso das mesmas. A reserva das salas é feita através do google calendar. Para reservar uma sala basta verificar se o horário desejado está disponível e então mandar um invite para a sala como você mandaria para as outras pessoas que devem estar presentes na reunião. Caso a sala esteja disponível ela automaticamente aceitara o convite assim bloqueando a agenda da sala.

Salas 11 andar:
-Sala varsóvia
-Sala são Paulo
- Sala Knoxville
-Salinha 1
-Salinha 2
-Salinha 3

Salas 14 andar:

**Comment by MarcoWorms** [comment]
Salas do 14:
-Sonic
-Zelda
-Metroid
-Donkey Kong
-Triforce

**Comment by xduh** [comment]
Fixer on PR #8
